fit = umap.UMAP(min_dist=.2, n_neighbors=15, n_components=2)
u = fit.fit_transform(x_rma.transpose())
fig = plt.figure()
ax = fig.add_subplot(111)
ax.scatter(u[:, 0], u[:, 1], c=c, cmap='Accent', alpha=1.0)
plt.scatter([], [], [], c=[], cmap='Accent')
cbar = plt.colorbar(boundaries=np.arange(8) - 0.5)
cbar.set_ticks(np.arange(7))
cbar.set_ticklabels(studies)
plt.title('UMAP embedding of 2886 microarray chips assaying 12,023 genes of 148 human volunteer subjects \n across 7 studies under 4 different inoculation regimes (HRV, RSV, H1N1, H3N2)',fontsize=20)
plt.axis('off')
plt.text(-3, -15, 'RMA Normalization', fontsize=20)
